---
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-webhook-service
  namespace: sitewhere-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
