apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: sitewhere-system/sitewhere-serving-cert
  name: sitewhere-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: sitewhere-webhook-service
      namespace: sitewhere-system
      path: /mutate-sitewhere-io-v1alpha4-sitewhereinstance
  failurePolicy: Fail
  name: msitewhereinstance.kb.io
  rules:
  - apiGroups:
    - sitewhere.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - instances
  sideEffects: None
