---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: sitewhere-system/sitewhere-serving-cert
  name: sitewhere-validating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: sitewhere-webhook-service
        namespace: sitewhere-system
        path: /validate-sitewhere-io-v1alpha4-sitewhereinstance
    failurePolicy: Fail
    name: vsitewhereinstance.kb.io
    rules:
      - apiGroups:
          - sitewhere.io
        apiVersions:
          - v1alpha4
        operations:
          - CREATE
          - UPDATE
        resources:
          - instances
