language: go
sudo: false
matrix:
  include:
    # "1.x" always refers to the latest Go version, inc. the patch release.
    # e.g. "1.x" is 1.11 until 1.11.1 is available.
    - go: 1.x
      env: LATEST=true
    - go: 1.14.x
    - go: tip
  allow_failures:
    - go: tip

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  -  # skip

script:
  - go get -t -v ./...
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  # Only build binaries from the latest Go release.
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="swctl.{{.OS}}.{{.Arch}}" -ldflags "-w -extldflags "-static" -X github.com/sitewhere/swctl/internal/version.commit=`git rev-parse --short HEAD` -X github.com/sitewhere/swctl/internal/version.date=$(date +'%Y-%m-%d_%T') -X github.com/sitewhere/swctl/internal/version.version=$(git describe --tags `git rev-list --tags --max-count=1`)" -verbose ./...; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh failure $WEBHOOK_URL"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AHupKcXqXgblqVLVYZ/C1Z5H9po4vpP6aAmWIxlWcHqE+b4TPmHzQSqjA5BsZehBi/8/WSmWnS7kJ0xNYtdjUe9W3y7CM6s42OCxEGSDM1w/TbTsioz4AeN34zkUhpMSGlHElyKoUFZalr2dvWBROkzZhB1eDyO2XsyWUZnaC0HeFI7f2MyC9ULmN/bss9xXVr+h6ag6IezCgwYZ6aigj+f9Acjk4sjQZKUmGU0fO1FljmebpbgrrVA0uRam9bhY8iONqGEuwKZvOaBeNGV9GCoocfF1blnZjU1nuvdVmas938ADIc1B+HKroKOMvIk/HEM6XccTghipur/hGVSH2knd7U17WbqqDWAELp22zv9gStUk4KYjyrEqzxGum8RDCLvRcMgvZ+BWxqoIrHpm5tjmT1hcwKYF3hgESkG9siOyIdTz/lIlChrrSMTRWtdwtZofrE5DUR/dKhPLmSsglWc6ru6lJWdtl0AzmTHmgrfSfatm5/7DdUyRST80sr5151WhgWsq7EMAMmBM8ft/9x4+HjP2ZErwiOht3DywiPONs7ysE4EZ04dnEjuV0t0+58ptXKZFCkfvRFMxddzSQE9+o/mjZv9RaOPBXp7lDCmP3RPlP4g7vfMtduORfZXsJIU+hfOsAzK1YgWZoSLaMw9tiS1bxb2JMqt1jvqSxUM=
  file:
    # The names of the binaries to output, based on the -output template passed to gox.
    - swctl.windows.amd64.exe
    - swctl.darwin.amd64
    - swctl.linux.amd64

  on:
    # What to repository to build
    repo: sitewhere/swctl
    tags: true
    condition: $LATEST = true
