# Source: sitewhere-infrastructure/templates/syncope-console-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitewhere-syncope-console
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:  
      name: "sitewhere-syncope-console"
      app.kubernetes.io/name: "sitewhere-syncope-console"
      app.kubernetes.io/instance: sitewhere-infrastructure
      sitewhere.io/role: "infrastructure"
      sitewhere.io/name: "syncope-console"
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: "sitewhere-syncope-console"
        app.kubernetes.io/name: "sitewhere-syncope-console"
        app.kubernetes.io/instance: sitewhere-infrastructure
        sitewhere.io/role: "infrastructure"
        sitewhere.io/name: "syncope-console"
    spec:
      containers:
      - name: syncope-console
        envFrom:
        - configMapRef:
           name: sitewhere-syncope-environment-config
        image: "apache/syncope-console:2.1.4"
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
