# Source: sitewhere-infrastructure/charts/redis-ha/templates/redis-ha-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-infrastructure-redis-ha
  namespace: sitewhere-system
  labels:
    app: redis-ha
    heritage: "Tiller"
    release: "sitewhere-infrastructure"
    chart: redis-ha-4.4.4
  annotations:
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    release: sitewhere-infrastructure
    app: redis-ha
