# Source: sitewhere-infrastructure/charts/redis-ha/templates/redis-ha-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sitewhere-infrastructure-redis-ha
  namespace: sitewhere-system
  labels:
    heritage: Tiller
    release: sitewhere-infrastructure
    chart: redis-ha-4.4.4
    app: sitewhere-infrastructure-redis-ha
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
