# Source: sitewhere-infrastructure/charts/nifi/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-infrastructure-nifi-headless
  namespace: sitewhere-system
  labels:
    app: "nifi"
    chart: "nifi-0.3.2"
    release: "sitewhere-infrastructure"
    heritage: "Tiller"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      name: http
    - port: 6007
      name: cluster
  selector:
    app: "nifi"
    release: "sitewhere-infrastructure"
