apiVersion: v1
kind: Secret
metadata:
  name: sitewhere-postgresql
  namespace: sitewhere-system
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-9.1.1
    app.kubernetes.io/instance: sitewhere
    app.kubernetes.io/managed-by: swctl
type: Opaque
data:
  postgresql-password: "cGFzc3dvcmQ="
