apiVersion: v1
kind: Service
metadata:
  name: sitewhere-postgresql-headless
  namespace: sitewhere-system
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-9.1.1
    app.kubernetes.io/instance: sitewhere
    app.kubernetes.io/managed-by: swctl
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: sitewhere
