# Source: sitewhere-infrastructure/charts/postgresql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-postgresql
  namespace: sitewhere-system
  labels:
    app: postgresql
spec:
  type: LoadBalancer
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: "sitewhere-infrastructure"
    role: master
