# Source: sitewhere-infrastructure/charts/influxdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-infrastructure-influxdb
  labels:
    helm.sh/chart: influxdb-4.8.1
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: sitewhere-infrastructure
    app.kubernetes.io/version: "1.8.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 8086
      targetPort: api
    - name: rpc
      port: 8088
      targetPort: rpc
  selector:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: sitewhere-infrastructure
