# Source: sitewhere-keycloak/charts/keycloak/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-keycloak-headless
  namespace: sitewhere-system
  labels:
    helm.sh/chart: keycloak-9.6.1
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/version: "11.0.2"
    app.kubernetes.io/managed-by: swctl
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
