apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-kafka-broker
  labels:
    app: strimzi
    chart: strimzi-kafka-operator-0.15.0
    component: broker-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
