# Source: sitewhere-infrastructure/templates/syncope-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitewhere-syncope
  namespace: sitewhere-system
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      name: "sitewhere-syncope"
      app.kubernetes.io/name: "sitewhere-syncope"
      app.kubernetes.io/instance: sitewhere-infrastructure
      sitewhere.io/role: "infrastructure"
      sitewhere.io/name: "syncope"
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: "sitewhere-syncope"
        app.kubernetes.io/name: "sitewhere-syncope"
        app.kubernetes.io/instance: sitewhere-infrastructure
        sitewhere.io/role: "infrastructure"
        sitewhere.io/name: "syncope"
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:9.6.5
          command: [
              "sh",
              "-c",
              "until pg_isready -h sitewhere-postgresql-headless -p 5432;
              do echo waiting for database; sleep 2; done;",
            ]
      containers:
        - name: syncope
          envFrom:
            - configMapRef:
                name: sitewhere-syncope-environment-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: syncope
                  key: postgresql-password
          image: "apache/syncope:2.1.4"
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/apache-syncope/security.properties
              subPath: security.properties
      volumes:
        - name: config-volume
          configMap:
            name: sitewhere-syncope-environment-config
      restartPolicy: Always
status: {}
