# Source: sitewhere-infrastructure/charts/influxdb/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sitewhere-infrastructure-influxdb
  labels:
    helm.sh/chart: influxdb-4.8.1
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: sitewhere-infrastructure
    app.kubernetes.io/version: "1.8.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
      app.kubernetes.io/instance: sitewhere-infrastructure
  serviceName: "sitewhere-infrastructure-influxdb"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
        app.kubernetes.io/instance: sitewhere-infrastructure
    spec:
      serviceAccountName: sitewhere-infrastructure-influxdb
      containers:
        - name: sitewhere-infrastructure-influxdb
          image: "influxdb:1.8.0-alpine"
          imagePullPolicy: "IfNotPresent"
          resources: {}

          ports:
            - name: api
              containerPort: 8086
            - name: rpc
              containerPort: 8088
          livenessProbe:
            httpGet:
              path: /ping
              port: api
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: api
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: sitewhere-infrastructure-influxdb-data
              mountPath: /var/lib/influxdb
            - name: config
              mountPath: /etc/influxdb
      volumes:
        - name: config
          configMap:
            name: sitewhere-infrastructure-influxdb
      # Cannot use existing claim in enterprise mode
  # Must use volume claim template in enterprise mode
  volumeClaimTemplates:
    - metadata:
        name: sitewhere-infrastructure-influxdb-data
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
