# Source: sitewhere-infrastructure/charts/influxdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-infrastructure-influxdb
  namespace: sitewhere-system
  labels:
    app.kubernetes.io/name: influxdb
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 8086
      targetPort: api
    - name: rpc
      port: 8088
      targetPort: rpc
  selector:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: sitewhere-infrastructure
