# Source: sitewhere-infrastructure/charts/nifi/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-infrastructure-nifi
  namespace: sitewhere-system
  labels:
    app: "nifi"
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      name: http
      targetPort: 8080
  selector:
    app: nifi
    release: sitewhere-infrastructure
