---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instanceconfigurations.templates.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: templates.sitewhere.io
  names:
    kind: InstanceConfigurationTemplate
    listKind: InstanceConfigurationTemplateList
    plural: instanceconfigurations
    singular: instanceconfiguration
    shortNames:
    - ict
    categories:
    - sitewhere-io
    - core-sitewhere-io
  scope: Cluster
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            instanceConfiguration:
              type: string
            webConfiguration:
              type: string
