---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenants.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: sitewhere.io
  names:
    kind: SiteWhereTenant
    listKind: SiteWhereTenantList
    plural: tenants
    singular: tenant
    shortNames:
    - swt
    categories:
    - sitewhere-io
    - core-sitewhere-io
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
