---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenantenginedatasets.templates.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: templates.sitewhere.io
  names:
    kind: TenantEngineDatasetTemplate
    listKind: TenantEngineDatasetTemplateList
    plural: tenantenginedatasets
    singular: tenantenginedataset
    shortNames:
      - tedt
    categories:
      - sitewhere-io
      - core-sitewhere-io
  scope: Cluster
  versions:
    - name: v1alpha4
      served: true
      storage: true
