---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenantengines.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: sitewhere.io
  names:
    kind: SiteWhereTenantEngine
    listKind: SiteWhereTenantEngineList
    plural: tenantengines
    singular: tenantengine
    shortNames:
    - swte
    categories:
    - sitewhere-io
    - core-sitewhere-io
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            configuration:
              type: object
        status:
          type: object
          properties:
            bootstrapState:
              type: string
