---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenantengineconfigurations.templates.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: templates.sitewhere.io
  names:
    kind: TenantEngineConfigurationTemplate
    listKind: TenantEngineConfigurationTemplateList
    plural: tenantengineconfigurations
    singular: tenantengineconfiguration
    shortNames:
    - tect
    categories:
    - sitewhere-io
    - core-sitewhere-io
  scope: Cluster
  versions:
    - name: v1alpha3
      served: true
      storage: true
