---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instancedatasets.templates.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: templates.sitewhere.io
  names:
    kind: InstanceDatasetTemplate
    listKind: InstanceDatasetTemplateList
    plural: instancedatasets
    singular: instancedataset
    shortNames:
      - idt
    categories:
      - sitewhere-io
      - core-sitewhere-io
  scope: Cluster
  versions:
    - name: v1alpha4
      served: true
      storage: true
