---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scripttemplates.scripting.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: scripting.sitewhere.io
  names:
    kind: SiteWhereScriptTemplate
    listKind: SiteWhereScriptTemplateList
    plural: scripttemplates
    singular: scripttemplate
    shortNames:
      - swscrt
    categories:
      - sitewhere-io
      - core-sitewhere-io
  scope: Cluster
  versions:
    - name: v1alpha4
      served: true
      storage: true
