---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scriptversions.scripting.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: scripting.sitewhere.io
  names:
    kind: SiteWhereScriptVersion
    listKind: SiteWhereScriptVersionList
    plural: scriptversions
    singular: scriptversion
    shortNames:
      - swscrv
    categories:
      - sitewhere-io
      - core-sitewhere-io
  scope: Namespaced
  versions:
    - name: v1alpha4
      served: true
      storage: true
