---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenantdatasets.templates.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: templates.sitewhere.io
  names:
    kind: TenantDatasetTemplate
    listKind: TenantDatasetTemplateList
    plural: tenantdatasets
    singular: tenantdataset
    shortNames:
    - tdt
    categories:
    - sitewhere-io
    - core-sitewhere-io
  scope: Cluster
  versions:
    - name: v1alpha3
      served: true
      storage: true
