---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scripts.scripting.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: scripting.sitewhere.io
  names:
    kind: SiteWhereScript
    listKind: SiteWhereScriptList
    plural: scripts
    singular: script
    shortNames:
    - swscr
    categories:
    - sitewhere-io
    - core-sitewhere-io
  scope: Namespaced
  versions:
    - name: v1alpha3
      served: true
      storage: true
